# Generated by Django 4.2.20 on 2025-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=13, unique=True)),
                ('codigo_barras', models.ImageField(blank=True, null=True, upload_to='codigos_barras/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_equipos/')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fondo_adquisicion', models.CharField(choices=[('SEP', 'SEP'), ('PIE', 'PIE'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('prestamo_activo', models.BooleanField(default=False)),
                ('nombre_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio_prestamo', models.DateField(blank=True, null=True)),
                ('fecha_fin_prestamo', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
