# Generated by Django 4.2.20 on 2025-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='subvencion_escolar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
