# Generated by Django 4.2.20 on 2025-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_subvencion_escolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='subvencion_escolar',
        ),
        migrations.AddField(
            model_name='inventario',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('en mantenimiento', 'En mantenimiento'), ('dañado', 'Dañado'), ('de_baja', 'De baja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fondo_adquisicion',
            field=models.CharField(choices=[('Sep', 'SEP'), ('Pie', 'PIE'), ('Sub Esc', 'SUB ESC'), ('Otro', 'OTRO')], default='OTRO', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo_equipo',
            field=models.CharField(choices=[('audio', 'Audio'), ('cámara', 'Cámara'), ('impresora', 'Impresora'), ('notebook', 'Notebook'), ('otros', 'Otros'), ('pc', 'PC'), ('proyector', 'Proyector'), ('tv', 'TV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(choices=[('bodega', 'Bodega'), ('capellanía', 'Capellanía'), ('comedor', 'Comedor'), ('computación', 'Computación'), ('dirección', 'Dirección'), ('inspectoría', 'Inspectoría'), ('integración', 'Integración'), ('patio', 'Patio'), ('pmi', 'PMI'), ('prebásica', 'Prebásica'), ('sala 1', 'Sala 1'), ('sala 2', 'Sala 2'), ('sala 3', 'Sala 3'), ('sala profesores', 'Sala Profesores'), ('sala taller', 'Sala Taller'), ('secretaría', 'Secretaría'), ('templo', 'Templo'), ('utp', 'UTP')], max_length=100),
        ),
    ]
