# Generated by Django 4.2.20 on 2025-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_inventario_subvencion_escolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('En mantenimiento', 'En mantenimiento'), ('Dañado', 'Dañado'), ('De baja', 'De baja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo_equipo',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Cámara', 'Cámara'), ('Impresora', 'Impresora'), ('Notebook', 'Notebook'), ('Otros', 'Otros'), ('PC', 'PC'), ('Proyector', 'Proyector'), ('Tv', 'TV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(choices=[('Bodega', 'Bodega'), ('Capellanía', 'Capellanía'), ('Comedor', 'Comedor'), ('Computación', 'Computación'), ('Dirección', 'Dirección'), ('Inspectoría', 'Inspectoría'), ('Integración', 'Integración'), ('Patio', 'Patio'), ('PMI', 'PMI'), ('Prebásica', 'Prebásica'), ('Sala 1', 'Sala 1'), ('Sala 2', 'Sala 2'), ('Sala 3', 'Sala 3'), ('Sala Profesores', 'Sala Profesores'), ('Sala Taller', 'Sala Taller'), ('Secretaría', 'Secretaría'), ('Templo', 'Templo'), ('UTP', 'UTP')], max_length=100),
        ),
    ]
